/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PRES"
 * 	found in "../../../../utils/ISO8823-PRESENTATION.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Abort_type_H_
#define	_Abort_type_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ARU-PPDU.h"
#include "ARP-PPDU.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Abort_type_PR {
	Abort_type_PR_NOTHING,	/* No components present */
	Abort_type_PR_aru_ppdu,
	Abort_type_PR_arp_ppdu
} Abort_type_PR;

/* Abort-type */
typedef struct Abort_type {
	Abort_type_PR present;
	union Abort_type_u {
		ARU_PPDU_t	 aru_ppdu;
		ARP_PPDU_t	 arp_ppdu;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Abort_type_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Abort_type;

#ifdef __cplusplus
}
#endif

#endif	/* _Abort_type_H_ */
#include <asn_internal.h>
