/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PRES"
 * 	found in "../../../../utils/ISO8823-PRESENTATION.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AC_PPDU_H_
#define	_AC_PPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Context_list;
struct Presentation_context_deletion_list;
struct User_data;

/* AC-PPDU */
typedef struct AC_PPDU {
	struct Context_list	*presentation_context_addition_list	/* OPTIONAL */;
	struct Presentation_context_deletion_list	*presentation_context_deletion_list	/* OPTIONAL */;
	struct User_data	*user_data	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AC_PPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AC_PPDU;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Presentation-context-addition-list.h"
#include "Presentation-context-deletion-list.h"
#include "User-data.h"

#endif	/* _AC_PPDU_H_ */
#include <asn_internal.h>
