/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Reliable-Transfer-APDU"
 * 	found in "/tmp/wireshark/epan/dissectors/asn1/rtse/rtse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AdditionalReferenceInformation_H_
#define	_AdditionalReferenceInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <T61String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AdditionalReferenceInformation */
typedef T61String_t	 AdditionalReferenceInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AdditionalReferenceInformation;
asn_struct_free_f AdditionalReferenceInformation_free;
asn_struct_print_f AdditionalReferenceInformation_print;
asn_constr_check_f AdditionalReferenceInformation_constraint;
ber_type_decoder_f AdditionalReferenceInformation_decode_ber;
der_type_encoder_f AdditionalReferenceInformation_encode_der;
xer_type_decoder_f AdditionalReferenceInformation_decode_xer;
xer_type_encoder_f AdditionalReferenceInformation_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AdditionalReferenceInformation_H_ */
#include <asn_internal.h>
