/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PRES"
 * 	found in "../../../../utils/ISO8823-PRESENTATION.asn"
 * 	`asn1c -fcompound-names`
 */

#include "ARP-PPDU.h"

static asn_TYPE_member_t asn_MBR_ARP_PPDU_1[] = {
	{ ATF_POINTER, 2, offsetof(struct ARP_PPDU, provider_reason),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Abort_reason,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"provider-reason"
		},
	{ ATF_POINTER, 1, offsetof(struct ARP_PPDU, event_identifier),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Event_identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"event-identifier"
		},
};
static const ber_tlv_tag_t asn_DEF_ARP_PPDU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ARP_PPDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* provider-reason */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* event-identifier */
};
static asn_SEQUENCE_specifics_t asn_SPC_ARP_PPDU_specs_1 = {
	sizeof(struct ARP_PPDU),
	offsetof(struct ARP_PPDU, _asn_ctx),
	asn_MAP_ARP_PPDU_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ARP_PPDU = {
	"ARP-PPDU",
	"ARP-PPDU",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ARP_PPDU_tags_1,
	sizeof(asn_DEF_ARP_PPDU_tags_1)
		/sizeof(asn_DEF_ARP_PPDU_tags_1[0]), /* 1 */
	asn_DEF_ARP_PPDU_tags_1,	/* Same as above */
	sizeof(asn_DEF_ARP_PPDU_tags_1)
		/sizeof(asn_DEF_ARP_PPDU_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ARP_PPDU_1,
	2,	/* Elements count */
	&asn_SPC_ARP_PPDU_specs_1	/* Additional specs */
};

