/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PRES"
 * 	found in "../../../../utils/ISO8823-PRESENTATION.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ARP_PPDU_H_
#define	_ARP_PPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Abort-reason.h"
#include "Event-identifier.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ARP-PPDU */
typedef struct ARP_PPDU {
	Abort_reason_t	*provider_reason	/* OPTIONAL */;
	Event_identifier_t	*event_identifier	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ARP_PPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ARP_PPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _ARP_PPDU_H_ */
#include <asn_internal.h>
