/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PRES"
 * 	found in "../../../../utils/ISO8823-PRESENTATION.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ARU_PPDU_H_
#define	_ARU_PPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ARU_PPDU_PR {
	ARU_PPDU_PR_NOTHING,	/* No components present */
	ARU_PPDU_PR_normal_mode_parameters
} ARU_PPDU_PR;

/* Forward declarations */
struct Presentation_context_identifier_list;
struct User_data;

/* ARU-PPDU */
typedef struct ARU_PPDU {
	ARU_PPDU_PR present;
	union ARU_PPDU_u {
		struct ARU_PPDU__normal_mode_parameters {
			struct Presentation_context_identifier_list	*presentation_context_identifier_list	/* OPTIONAL */;
			struct User_data	*user_data	/* OPTIONAL */;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} normal_mode_parameters;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ARU_PPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ARU_PPDU;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Presentation-context-identifier-list.h"
#include "User-data.h"

#endif	/* _ARU_PPDU_H_ */
#include <asn_internal.h>
