/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Reliable-Transfer-APDU"
 * 	found in "/tmp/wireshark/epan/dissectors/asn1/rtse/rtse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_CallingSSuserReference_H_
#define	_CallingSSuserReference_H_


#include <asn_application.h>

/* Including external dependencies */
#include <T61String.h>
#include <OCTET_STRING.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CallingSSuserReference_PR {
	CallingSSuserReference_PR_NOTHING,	/* No components present */
	CallingSSuserReference_PR_t61String,
	CallingSSuserReference_PR_octetString
} CallingSSuserReference_PR;

/* CallingSSuserReference */
typedef struct CallingSSuserReference {
	CallingSSuserReference_PR present;
	union CallingSSuserReference_u {
		T61String_t	 t61String;
		OCTET_STRING_t	 octetString;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CallingSSuserReference_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CallingSSuserReference;

#ifdef __cplusplus
}
#endif

#endif	/* _CallingSSuserReference_H_ */
#include <asn_internal.h>
