/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PRES"
 * 	found in "../../../../utils/ISO8823-PRESENTATION.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Calling_presentation_selector_H_
#define	_Calling_presentation_selector_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Presentation-selector.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Calling-presentation-selector */
typedef Presentation_selector_t	 Calling_presentation_selector_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Calling_presentation_selector;
asn_struct_free_f Calling_presentation_selector_free;
asn_struct_print_f Calling_presentation_selector_print;
asn_constr_check_f Calling_presentation_selector_constraint;
ber_type_decoder_f Calling_presentation_selector_decode_ber;
der_type_encoder_f Calling_presentation_selector_encode_der;
xer_type_decoder_f Calling_presentation_selector_decode_xer;
xer_type_encoder_f Calling_presentation_selector_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Calling_presentation_selector_H_ */
#include <asn_internal.h>
