/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Reliable-Transfer-APDU"
 * 	found in "/tmp/wireshark/epan/dissectors/asn1/rtse/rtse.asn"
 * 	`asn1c -fcompound-names`
 */

#include "CallingSSuserReference.h"

static asn_TYPE_member_t asn_MBR_CallingSSuserReference_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CallingSSuserReference, choice.t61String),
		(ASN_TAG_CLASS_UNIVERSAL | (20 << 2)),
		0,
		&asn_DEF_T61String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"t61String"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CallingSSuserReference, choice.octetString),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"octetString"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_CallingSSuserReference_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* octetString */
    { (ASN_TAG_CLASS_UNIVERSAL | (20 << 2)), 0, 0, 0 } /* t61String */
};
static asn_CHOICE_specifics_t asn_SPC_CallingSSuserReference_specs_1 = {
	sizeof(struct CallingSSuserReference),
	offsetof(struct CallingSSuserReference, _asn_ctx),
	offsetof(struct CallingSSuserReference, present),
	sizeof(((struct CallingSSuserReference *)0)->present),
	asn_MAP_CallingSSuserReference_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_CallingSSuserReference = {
	"CallingSSuserReference",
	"CallingSSuserReference",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_CallingSSuserReference_1,
	2,	/* Elements count */
	&asn_SPC_CallingSSuserReference_specs_1	/* Additional specs */
};

