/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Reliable-Transfer-APDU"
 * 	found in "/tmp/wireshark/epan/dissectors/asn1/rtse/rtse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ConnectionData_H_
#define	_ConnectionData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ANY.h>
#include "SessionConnectionIdentifier.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ConnectionData_PR {
	ConnectionData_PR_NOTHING,	/* No components present */
	ConnectionData_PR_open,
	ConnectionData_PR_recover
} ConnectionData_PR;

/* ConnectionData */
typedef struct ConnectionData {
	ConnectionData_PR present;
	union ConnectionData_u {
		ANY_t	 open;
		SessionConnectionIdentifier_t	 recover;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConnectionData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConnectionData;

#ifdef __cplusplus
}
#endif

#endif	/* _ConnectionData_H_ */
#include <asn_internal.h>
