/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PRES"
 * 	found in "../../../../utils/ISO8823-PRESENTATION.asn"
 * 	`asn1c -fcompound-names`
 */

#include "CPA-PPDU.h"

static asn_TYPE_member_t asn_MBR_normal_mode_parameters_3[] = {
	{ ATF_POINTER, 8, offsetof(struct CPA_PPDU__normal_mode_parameters, protocol_version),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Protocol_version,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"protocol-version"
		},
	{ ATF_POINTER, 7, offsetof(struct CPA_PPDU__normal_mode_parameters, responding_presentation_selector),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Responding_presentation_selector,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"responding-presentation-selector"
		},
	{ ATF_POINTER, 6, offsetof(struct CPA_PPDU__normal_mode_parameters, presentation_context_definition_result_list),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Presentation_context_definition_result_list,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"presentation-context-definition-result-list"
		},
	{ ATF_POINTER, 5, offsetof(struct CPA_PPDU__normal_mode_parameters, presentation_requirements),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Presentation_requirements,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"presentation-requirements"
		},
	{ ATF_POINTER, 4, offsetof(struct CPA_PPDU__normal_mode_parameters, user_session_requirements),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_User_session_requirements,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"user-session-requirements"
		},
	{ ATF_POINTER, 3, offsetof(struct CPA_PPDU__normal_mode_parameters, protocol_options),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Protocol_options,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"protocol-options"
		},
	{ ATF_POINTER, 2, offsetof(struct CPA_PPDU__normal_mode_parameters, responders_nominated_context),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Presentation_context_identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"responders-nominated-context"
		},
	{ ATF_POINTER, 1, offsetof(struct CPA_PPDU__normal_mode_parameters, user_data),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_User_data,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"user-data"
		},
};
static const ber_tlv_tag_t asn_DEF_normal_mode_parameters_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_normal_mode_parameters_tag2el_3[] = {
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 7, 0, 0 }, /* simply-encoded-data */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 7, 0, 0 }, /* fully-encoded-data */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* protocol-version */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 }, /* responding-presentation-selector */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 2, 0, 0 }, /* presentation-context-definition-result-list */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 3, 0, 0 }, /* presentation-requirements */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 4, 0, 0 }, /* user-session-requirements */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 5, 0, 0 }, /* protocol-options */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 6, 0, 0 } /* responders-nominated-context */
};
static asn_SEQUENCE_specifics_t asn_SPC_normal_mode_parameters_specs_3 = {
	sizeof(struct CPA_PPDU__normal_mode_parameters),
	offsetof(struct CPA_PPDU__normal_mode_parameters, _asn_ctx),
	asn_MAP_normal_mode_parameters_tag2el_3,
	9,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_normal_mode_parameters_3 = {
	"normal-mode-parameters",
	"normal-mode-parameters",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_normal_mode_parameters_tags_3,
	sizeof(asn_DEF_normal_mode_parameters_tags_3)
		/sizeof(asn_DEF_normal_mode_parameters_tags_3[0]) - 1, /* 1 */
	asn_DEF_normal_mode_parameters_tags_3,	/* Same as above */
	sizeof(asn_DEF_normal_mode_parameters_tags_3)
		/sizeof(asn_DEF_normal_mode_parameters_tags_3[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_normal_mode_parameters_3,
	8,	/* Elements count */
	&asn_SPC_normal_mode_parameters_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_CPA_PPDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CPA_PPDU, mode_selector),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Mode_selector,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mode-selector"
		},
	{ ATF_POINTER, 1, offsetof(struct CPA_PPDU, normal_mode_parameters),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_normal_mode_parameters_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"normal-mode-parameters"
		},
};
static const ber_tlv_tag_t asn_DEF_CPA_PPDU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CPA_PPDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mode-selector */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 } /* normal-mode-parameters */
};
static const uint8_t asn_MAP_CPA_PPDU_mmap_1[(2 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(1 << 7) | (0 << 6)
};
static asn_SET_specifics_t asn_SPC_CPA_PPDU_specs_1 = {
	sizeof(struct CPA_PPDU),
	offsetof(struct CPA_PPDU, _asn_ctx),
	offsetof(struct CPA_PPDU, _presence_map),
	asn_MAP_CPA_PPDU_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_CPA_PPDU_tag2el_1,	/* Same as above */
	2,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(unsigned int *)asn_MAP_CPA_PPDU_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_CPA_PPDU = {
	"CPA-PPDU",
	"CPA-PPDU",
	SET_free,
	SET_print,
	SET_constraint,
	SET_decode_ber,
	SET_encode_der,
	SET_decode_xer,
	SET_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_CPA_PPDU_tags_1,
	sizeof(asn_DEF_CPA_PPDU_tags_1)
		/sizeof(asn_DEF_CPA_PPDU_tags_1[0]), /* 1 */
	asn_DEF_CPA_PPDU_tags_1,	/* Same as above */
	sizeof(asn_DEF_CPA_PPDU_tags_1)
		/sizeof(asn_DEF_CPA_PPDU_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_CPA_PPDU_1,
	2,	/* Elements count */
	&asn_SPC_CPA_PPDU_specs_1	/* Additional specs */
};

