/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PRES"
 * 	found in "../../../../utils/ISO8823-PRESENTATION.asn"
 * 	`asn1c -fcompound-names`
 */

#include "CPR-PPDU.h"

static asn_TYPE_member_t asn_MBR_normal_mode_parameters_2[] = {
	{ ATF_POINTER, 6, offsetof(struct CPR_PPDU__normal_mode_parameters, protocol_version),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Protocol_version,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"protocol-version"
		},
	{ ATF_POINTER, 5, offsetof(struct CPR_PPDU__normal_mode_parameters, responding_presentation_selector),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Responding_presentation_selector,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"responding-presentation-selector"
		},
	{ ATF_POINTER, 4, offsetof(struct CPR_PPDU__normal_mode_parameters, presentation_context_definition_result_list),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Presentation_context_definition_result_list,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"presentation-context-definition-result-list"
		},
	{ ATF_POINTER, 3, offsetof(struct CPR_PPDU__normal_mode_parameters, default_context_result),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Default_context_result,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"default-context-result"
		},
	{ ATF_POINTER, 2, offsetof(struct CPR_PPDU__normal_mode_parameters, provider_reason),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Provider_reason,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"provider-reason"
		},
	{ ATF_POINTER, 1, offsetof(struct CPR_PPDU__normal_mode_parameters, user_data),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_User_data,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"user-data"
		},
};
static const ber_tlv_tag_t asn_DEF_normal_mode_parameters_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_normal_mode_parameters_tag2el_2[] = {
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 5, 0, 0 }, /* simply-encoded-data */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 5, 0, 0 }, /* fully-encoded-data */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* protocol-version */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 }, /* responding-presentation-selector */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 2, 0, 0 }, /* presentation-context-definition-result-list */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 3, 0, 0 }, /* default-context-result */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 4, 0, 0 } /* provider-reason */
};
static asn_SEQUENCE_specifics_t asn_SPC_normal_mode_parameters_specs_2 = {
	sizeof(struct CPR_PPDU__normal_mode_parameters),
	offsetof(struct CPR_PPDU__normal_mode_parameters, _asn_ctx),
	asn_MAP_normal_mode_parameters_tag2el_2,
	7,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_normal_mode_parameters_2 = {
	"normal-mode-parameters",
	"normal-mode-parameters",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_normal_mode_parameters_tags_2,
	sizeof(asn_DEF_normal_mode_parameters_tags_2)
		/sizeof(asn_DEF_normal_mode_parameters_tags_2[0]), /* 1 */
	asn_DEF_normal_mode_parameters_tags_2,	/* Same as above */
	sizeof(asn_DEF_normal_mode_parameters_tags_2)
		/sizeof(asn_DEF_normal_mode_parameters_tags_2[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_normal_mode_parameters_2,
	6,	/* Elements count */
	&asn_SPC_normal_mode_parameters_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_CPR_PPDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CPR_PPDU, choice.normal_mode_parameters),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_normal_mode_parameters_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"normal-mode-parameters"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_CPR_PPDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* normal-mode-parameters */
};
static asn_CHOICE_specifics_t asn_SPC_CPR_PPDU_specs_1 = {
	sizeof(struct CPR_PPDU),
	offsetof(struct CPR_PPDU, _asn_ctx),
	offsetof(struct CPR_PPDU, present),
	sizeof(((struct CPR_PPDU *)0)->present),
	asn_MAP_CPR_PPDU_tag2el_1,
	1,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_CPR_PPDU = {
	"CPR-PPDU",
	"CPR-PPDU",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_CPR_PPDU_1,
	1,	/* Elements count */
	&asn_SPC_CPR_PPDU_specs_1	/* Additional specs */
};

