/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PRES"
 * 	found in "../../../../utils/ISO8823-PRESENTATION.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Default_context_name_H_
#define	_Default_context_name_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Abstract-syntax-name.h"
#include "Transfer-syntax-name.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Default-context-name */
typedef struct Default_context_name {
	Abstract_syntax_name_t	 abstract_syntax_name;
	Transfer_syntax_name_t	 transfer_syntax_name;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Default_context_name_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Default_context_name;

#ifdef __cplusplus
}
#endif

#endif	/* _Default_context_name_H_ */
#include <asn_internal.h>
