/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PRES"
 * 	found in "../../../../utils/ISO8823-PRESENTATION.asn"
 * 	`asn1c -fcompound-names`
 */

#include "PDV-list.h"

static asn_TYPE_member_t asn_MBR_presentation_data_values_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PDV_list__presentation_data_values, choice.single_ASN1_type),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ANY,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"single-ASN1-type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDV_list__presentation_data_values, choice.octet_aligned),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"octet-aligned"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDV_list__presentation_data_values, choice.arbitrary),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"arbitrary"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_presentation_data_values_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* single-ASN1-type */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* octet-aligned */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* arbitrary */
};
static asn_CHOICE_specifics_t asn_SPC_presentation_data_values_specs_4 = {
	sizeof(struct PDV_list__presentation_data_values),
	offsetof(struct PDV_list__presentation_data_values, _asn_ctx),
	offsetof(struct PDV_list__presentation_data_values, present),
	sizeof(((struct PDV_list__presentation_data_values *)0)->present),
	asn_MAP_presentation_data_values_tag2el_4,
	3,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_presentation_data_values_4 = {
	"presentation-data-values",
	"presentation-data-values",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_presentation_data_values_4,
	3,	/* Elements count */
	&asn_SPC_presentation_data_values_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_PDV_list_1[] = {
	{ ATF_POINTER, 1, offsetof(struct PDV_list, transfer_syntax_name),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_Transfer_syntax_name,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"transfer-syntax-name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDV_list, presentation_context_identifier),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Presentation_context_identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"presentation-context-identifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDV_list, presentation_data_values),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_presentation_data_values_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"presentation-data-values"
		},
};
static const ber_tlv_tag_t asn_DEF_PDV_list_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PDV_list_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* presentation-context-identifier */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 }, /* transfer-syntax-name */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 2, 0, 0 }, /* single-ASN1-type */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 2, 0, 0 }, /* octet-aligned */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* arbitrary */
};
static asn_SEQUENCE_specifics_t asn_SPC_PDV_list_specs_1 = {
	sizeof(struct PDV_list),
	offsetof(struct PDV_list, _asn_ctx),
	asn_MAP_PDV_list_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PDV_list = {
	"PDV-list",
	"PDV-list",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PDV_list_tags_1,
	sizeof(asn_DEF_PDV_list_tags_1)
		/sizeof(asn_DEF_PDV_list_tags_1[0]), /* 1 */
	asn_DEF_PDV_list_tags_1,	/* Same as above */
	sizeof(asn_DEF_PDV_list_tags_1)
		/sizeof(asn_DEF_PDV_list_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PDV_list_1,
	3,	/* Elements count */
	&asn_SPC_PDV_list_specs_1	/* Additional specs */
};

