/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PRES"
 * 	found in "../../../../utils/ISO8823-PRESENTATION.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Presentation_selector_H_
#define	_Presentation_selector_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Presentation-selector */
typedef OCTET_STRING_t	 Presentation_selector_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Presentation_selector;
asn_struct_free_f Presentation_selector_free;
asn_struct_print_f Presentation_selector_print;
asn_constr_check_f Presentation_selector_constraint;
ber_type_decoder_f Presentation_selector_decode_ber;
der_type_encoder_f Presentation_selector_encode_der;
xer_type_decoder_f Presentation_selector_decode_xer;
xer_type_encoder_f Presentation_selector_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Presentation_selector_H_ */
#include <asn_internal.h>
