/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Reliable-Transfer-APDU"
 * 	found in "/tmp/wireshark/epan/dissectors/asn1/rtse/rtse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RefuseReason_H_
#define	_RefuseReason_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RefuseReason {
	RefuseReason_rtsBusy	= 0,
	RefuseReason_cannotRecover	= 1,
	RefuseReason_validationFailure	= 2,
	RefuseReason_unacceptableDialogueMode	= 3
} e_RefuseReason;

/* RefuseReason */
typedef long	 RefuseReason_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RefuseReason;
asn_struct_free_f RefuseReason_free;
asn_struct_print_f RefuseReason_print;
asn_constr_check_f RefuseReason_constraint;
ber_type_decoder_f RefuseReason_decode_ber;
der_type_encoder_f RefuseReason_encode_der;
xer_type_decoder_f RefuseReason_decode_xer;
xer_type_encoder_f RefuseReason_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RefuseReason_H_ */
#include <asn_internal.h>
