/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PRES"
 * 	found in "../../../../utils/ISO8823-PRESENTATION.asn"
 * 	`asn1c -fcompound-names`
 */

#include "RS-PPDU.h"

static asn_TYPE_member_t asn_MBR_RS_PPDU_1[] = {
	{ ATF_POINTER, 2, offsetof(struct RS_PPDU, presentation_context_identifier_list),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Presentation_context_identifier_list,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"presentation-context-identifier-list"
		},
	{ ATF_POINTER, 1, offsetof(struct RS_PPDU, user_data),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_User_data,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"user-data"
		},
};
static const ber_tlv_tag_t asn_DEF_RS_PPDU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RS_PPDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 1, 0, 0 }, /* simply-encoded-data */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 1, 0, 0 }, /* fully-encoded-data */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* presentation-context-identifier-list */
};
static asn_SEQUENCE_specifics_t asn_SPC_RS_PPDU_specs_1 = {
	sizeof(struct RS_PPDU),
	offsetof(struct RS_PPDU, _asn_ctx),
	asn_MAP_RS_PPDU_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_RS_PPDU = {
	"RS-PPDU",
	"RS-PPDU",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RS_PPDU_tags_1,
	sizeof(asn_DEF_RS_PPDU_tags_1)
		/sizeof(asn_DEF_RS_PPDU_tags_1[0]), /* 1 */
	asn_DEF_RS_PPDU_tags_1,	/* Same as above */
	sizeof(asn_DEF_RS_PPDU_tags_1)
		/sizeof(asn_DEF_RS_PPDU_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_RS_PPDU_1,
	2,	/* Elements count */
	&asn_SPC_RS_PPDU_specs_1	/* Additional specs */
};

