/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PRES"
 * 	found in "../../../../utils/ISO8823-PRESENTATION.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RSA_PPDU_H_
#define	_RSA_PPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Presentation_context_identifier_list;
struct User_data;

/* RSA-PPDU */
typedef struct RSA_PPDU {
	struct Presentation_context_identifier_list	*presentation_context_identifier_list	/* OPTIONAL */;
	struct User_data	*user_data	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RSA_PPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RSA_PPDU;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Presentation-context-identifier-list.h"
#include "User-data.h"

#endif	/* _RSA_PPDU_H_ */
#include <asn_internal.h>
