/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Reliable-Transfer-APDU"
 * 	found in "/tmp/wireshark/epan/dissectors/asn1/rtse/rtse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RTABapdu_H_
#define	_RTABapdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AbortReason.h"
#include <BIT_STRING.h>
#include <ANY.h>
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum RTABapdu_PR {
	RTABapdu_PR_abortReason,	/* Member abortReason is present */
	RTABapdu_PR_reflectedParameter,	/* Member reflectedParameter is present */
	RTABapdu_PR_userdataAB,	/* Member userdataAB is present */
} RTABapdu_PR;

/* RTABapdu */
typedef struct RTABapdu {
	AbortReason_t	*abortReason	/* OPTIONAL */;
	BIT_STRING_t	*reflectedParameter	/* OPTIONAL */;
	ANY_t	*userdataAB	/* OPTIONAL */;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pRTABapdu, RTABapdu_PR_x) */
	unsigned int _presence_map
		[((3+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RTABapdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RTABapdu;

#ifdef __cplusplus
}
#endif

#endif	/* _RTABapdu_H_ */
#include <asn_internal.h>
