/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Reliable-Transfer-APDU"
 * 	found in "/tmp/wireshark/epan/dissectors/asn1/rtse/rtse.asn"
 * 	`asn1c -fcompound-names`
 */

#include "RTOACapdu.h"

static int asn_DFL_2_set_0(int set_value, void **sptr) {
	long *st = *sptr;
	
	if(!st) {
		if(!set_value) return -1;	/* Not a default value */
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	if(set_value) {
		/* Install default value 0 */
		*st = 0;
		return 0;
	} else {
		/* Test default value 0 */
		return (*st == 0);
	}
}
static int asn_DFL_3_set_3(int set_value, void **sptr) {
	long *st = *sptr;
	
	if(!st) {
		if(!set_value) return -1;	/* Not a default value */
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	if(set_value) {
		/* Install default value 3 */
		*st = 3;
		return 0;
	} else {
		/* Test default value 3 */
		return (*st == 3);
	}
}
static asn_TYPE_member_t asn_MBR_RTOACapdu_1[] = {
	{ ATF_NOFLAGS, 2, offsetof(struct RTOACapdu, checkpointSize),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		asn_DFL_2_set_0,	/* DEFAULT 0 */
		"checkpointSize"
		},
	{ ATF_POINTER, 1, offsetof(struct RTOACapdu, windowSize),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		asn_DFL_3_set_3,	/* DEFAULT 3 */
		"windowSize"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RTOACapdu, connectionDataAC),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ConnectionData,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"connectionDataAC"
		},
};
static const ber_tlv_tag_t asn_DEF_RTOACapdu_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RTOACapdu_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* checkpointSize */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* windowSize */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* connectionDataAC */
};
static const uint8_t asn_MAP_RTOACapdu_mmap_1[(3 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(0 << 7) | (0 << 6) | (1 << 5)
};
static asn_SET_specifics_t asn_SPC_RTOACapdu_specs_1 = {
	sizeof(struct RTOACapdu),
	offsetof(struct RTOACapdu, _asn_ctx),
	offsetof(struct RTOACapdu, _presence_map),
	asn_MAP_RTOACapdu_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_RTOACapdu_tag2el_1,	/* Same as above */
	3,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(unsigned int *)asn_MAP_RTOACapdu_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_RTOACapdu = {
	"RTOACapdu",
	"RTOACapdu",
	SET_free,
	SET_print,
	SET_constraint,
	SET_decode_ber,
	SET_encode_der,
	SET_decode_xer,
	SET_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RTOACapdu_tags_1,
	sizeof(asn_DEF_RTOACapdu_tags_1)
		/sizeof(asn_DEF_RTOACapdu_tags_1[0]), /* 1 */
	asn_DEF_RTOACapdu_tags_1,	/* Same as above */
	sizeof(asn_DEF_RTOACapdu_tags_1)
		/sizeof(asn_DEF_RTOACapdu_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_RTOACapdu_1,
	3,	/* Elements count */
	&asn_SPC_RTOACapdu_specs_1	/* Additional specs */
};

