/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Reliable-Transfer-APDU"
 * 	found in "/tmp/wireshark/epan/dissectors/asn1/rtse/rtse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RTOACapdu_H_
#define	_RTOACapdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "ConnectionData.h"
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum RTOACapdu_PR {
	RTOACapdu_PR_checkpointSize,	/* Member checkpointSize is present */
	RTOACapdu_PR_windowSize,	/* Member windowSize is present */
	RTOACapdu_PR_connectionDataAC,	/* Member connectionDataAC is present */
} RTOACapdu_PR;

/* RTOACapdu */
typedef struct RTOACapdu {
	long	 checkpointSize	/* DEFAULT 0 */;
	long	*windowSize	/* DEFAULT 3 */;
	ConnectionData_t	 connectionDataAC;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pRTOACapdu, RTOACapdu_PR_x) */
	unsigned int _presence_map
		[((3+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RTOACapdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RTOACapdu;

#ifdef __cplusplus
}
#endif

#endif	/* _RTOACapdu_H_ */
#include <asn_internal.h>
