/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Reliable-Transfer-APDU"
 * 	found in "/tmp/wireshark/epan/dissectors/asn1/rtse/rtse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RTORQapdu_H_
#define	_RTORQapdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "ConnectionData.h"
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum RTORQapdu_PR {
	RTORQapdu_PR_checkpointSize,	/* Member checkpointSize is present */
	RTORQapdu_PR_windowSize,	/* Member windowSize is present */
	RTORQapdu_PR_dialogueMode,	/* Member dialogueMode is present */
	RTORQapdu_PR_connectionDataRQ,	/* Member connectionDataRQ is present */
	RTORQapdu_PR_applicationProtocol,	/* Member applicationProtocol is present */
} RTORQapdu_PR;
typedef enum RTORQapdu__dialogueMode {
	RTORQapdu__dialogueMode_monologue	= 0,
	RTORQapdu__dialogueMode_twa	= 1
} e_RTORQapdu__dialogueMode;
typedef enum RTORQapdu__applicationProtocol {
	RTORQapdu__applicationProtocol_mts_transfer_protocol	= 12,
	RTORQapdu__applicationProtocol_mts_transfer_protocol_1984	= 1
} e_RTORQapdu__applicationProtocol;

/* RTORQapdu */
typedef struct RTORQapdu {
	long	 checkpointSize	/* DEFAULT 0 */;
	long	*windowSize	/* DEFAULT 3 */;
	long	 dialogueMode	/* DEFAULT 0 */;
	ConnectionData_t	 connectionDataRQ;
	long	*applicationProtocol	/* OPTIONAL */;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pRTORQapdu, RTORQapdu_PR_x) */
	unsigned int _presence_map
		[((5+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RTORQapdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RTORQapdu;

#ifdef __cplusplus
}
#endif

#endif	/* _RTORQapdu_H_ */
#include <asn_internal.h>
