/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Reliable-Transfer-APDU"
 * 	found in "/tmp/wireshark/epan/dissectors/asn1/rtse/rtse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RTSE_apdus_H_
#define	_RTSE_apdus_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RTORQapdu.h"
#include "RTOACapdu.h"
#include "RTORJapdu.h"
#include "RTTPapdu.h"
#include "RTTRapdu.h"
#include "RTABapdu.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RTSE_apdus_PR {
	RTSE_apdus_PR_NOTHING,	/* No components present */
	RTSE_apdus_PR_rtorq_apdu,
	RTSE_apdus_PR_rtoac_apdu,
	RTSE_apdus_PR_rtorj_apdu,
	RTSE_apdus_PR_rttp_apdu,
	RTSE_apdus_PR_rttr_apdu,
	RTSE_apdus_PR_rtab_apdu
} RTSE_apdus_PR;

/* RTSE-apdus */
typedef struct RTSE_apdus {
	RTSE_apdus_PR present;
	union RTSE_apdus_u {
		RTORQapdu_t	 rtorq_apdu;
		RTOACapdu_t	 rtoac_apdu;
		RTORJapdu_t	 rtorj_apdu;
		RTTPapdu_t	 rttp_apdu;
		RTTRapdu_t	 rttr_apdu;
		RTABapdu_t	 rtab_apdu;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RTSE_apdus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RTSE_apdus;

#ifdef __cplusplus
}
#endif

#endif	/* _RTSE_apdus_H_ */
#include <asn_internal.h>
