/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Reliable-Transfer-APDU"
 * 	found in "/tmp/wireshark/epan/dissectors/asn1/rtse/rtse.asn"
 * 	`asn1c -fcompound-names`
 */

#include "RTSE-apdus.h"

static asn_TYPE_member_t asn_MBR_RTSE_apdus_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RTSE_apdus, choice.rtorq_apdu),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RTORQapdu,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rtorq-apdu"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RTSE_apdus, choice.rtoac_apdu),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RTOACapdu,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rtoac-apdu"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RTSE_apdus, choice.rtorj_apdu),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RTORJapdu,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rtorj-apdu"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RTSE_apdus, choice.rttp_apdu),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_RTTPapdu,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rttp-apdu"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RTSE_apdus, choice.rttr_apdu),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_RTTRapdu,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rttr-apdu"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RTSE_apdus, choice.rtab_apdu),
		(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RTABapdu,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rtab-apdu"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_RTSE_apdus_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 3, 0, 0 }, /* rttp-apdu */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 4, 0, 0 }, /* rttr-apdu */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 0, 0, 0 }, /* rtorq-apdu */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 1, 0, 0 }, /* rtoac-apdu */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 2, 0, 0 }, /* rtorj-apdu */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 5, 0, 0 } /* rtab-apdu */
};
static asn_CHOICE_specifics_t asn_SPC_RTSE_apdus_specs_1 = {
	sizeof(struct RTSE_apdus),
	offsetof(struct RTSE_apdus, _asn_ctx),
	offsetof(struct RTSE_apdus, present),
	sizeof(((struct RTSE_apdus *)0)->present),
	asn_MAP_RTSE_apdus_tag2el_1,
	6,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_RTSE_apdus = {
	"RTSE-apdus",
	"RTSE-apdus",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_RTSE_apdus_1,
	6,	/* Elements count */
	&asn_SPC_RTSE_apdus_specs_1	/* Additional specs */
};

