/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Reliable-Transfer-APDU"
 * 	found in "/tmp/wireshark/epan/dissectors/asn1/rtse/rtse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RTTPapdu_H_
#define	_RTTPapdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RTTPapdu */
typedef long	 RTTPapdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RTTPapdu;
asn_struct_free_f RTTPapdu_free;
asn_struct_print_f RTTPapdu_print;
asn_constr_check_f RTTPapdu_constraint;
ber_type_decoder_f RTTPapdu_decode_ber;
der_type_encoder_f RTTPapdu_encode_der;
xer_type_decoder_f RTTPapdu_decode_xer;
xer_type_encoder_f RTTPapdu_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RTTPapdu_H_ */
#include <asn_internal.h>
