/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Reliable-Transfer-APDU"
 * 	found in "/tmp/wireshark/epan/dissectors/asn1/rtse/rtse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RTTRapdu_H_
#define	_RTTRapdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RTTRapdu */
typedef OCTET_STRING_t	 RTTRapdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RTTRapdu;
asn_struct_free_f RTTRapdu_free;
asn_struct_print_f RTTRapdu_print;
asn_constr_check_f RTTRapdu_constraint;
ber_type_decoder_f RTTRapdu_decode_ber;
der_type_encoder_f RTTRapdu_encode_der;
xer_type_decoder_f RTTRapdu_decode_xer;
xer_type_encoder_f RTTRapdu_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RTTRapdu_H_ */
#include <asn_internal.h>
