/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Reliable-Transfer-APDU"
 * 	found in "/tmp/wireshark/epan/dissectors/asn1/rtse/rtse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_SessionConnectionIdentifier_H_
#define	_SessionConnectionIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CallingSSuserReference.h"
#include "CommonReference.h"
#include "AdditionalReferenceInformation.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SessionConnectionIdentifier */
typedef struct SessionConnectionIdentifier {
	CallingSSuserReference_t	 callingSSuserReference;
	CommonReference_t	 commonReference;
	AdditionalReferenceInformation_t	*additionalReferenceInformation	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SessionConnectionIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SessionConnectionIdentifier;

#ifdef __cplusplus
}
#endif

#endif	/* _SessionConnectionIdentifier_H_ */
#include <asn_internal.h>
