/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Reliable-Transfer-APDU"
 * 	found in "/tmp/wireshark/epan/dissectors/asn1/rtse/rtse.asn"
 * 	`asn1c -fcompound-names`
 */

#include "SessionConnectionIdentifier.h"

static asn_TYPE_member_t asn_MBR_SessionConnectionIdentifier_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SessionConnectionIdentifier, callingSSuserReference),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_CallingSSuserReference,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"callingSSuserReference"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SessionConnectionIdentifier, commonReference),
		(ASN_TAG_CLASS_UNIVERSAL | (23 << 2)),
		0,
		&asn_DEF_CommonReference,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"commonReference"
		},
	{ ATF_POINTER, 1, offsetof(struct SessionConnectionIdentifier, additionalReferenceInformation),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AdditionalReferenceInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"additionalReferenceInformation"
		},
};
static const ber_tlv_tag_t asn_DEF_SessionConnectionIdentifier_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SessionConnectionIdentifier_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 0 }, /* octetString */
    { (ASN_TAG_CLASS_UNIVERSAL | (20 << 2)), 0, 0, 0 }, /* t61String */
    { (ASN_TAG_CLASS_UNIVERSAL | (23 << 2)), 1, 0, 0 }, /* commonReference */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 2, 0, 0 } /* additionalReferenceInformation */
};
static asn_SEQUENCE_specifics_t asn_SPC_SessionConnectionIdentifier_specs_1 = {
	sizeof(struct SessionConnectionIdentifier),
	offsetof(struct SessionConnectionIdentifier, _asn_ctx),
	asn_MAP_SessionConnectionIdentifier_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SessionConnectionIdentifier = {
	"SessionConnectionIdentifier",
	"SessionConnectionIdentifier",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SessionConnectionIdentifier_tags_1,
	sizeof(asn_DEF_SessionConnectionIdentifier_tags_1)
		/sizeof(asn_DEF_SessionConnectionIdentifier_tags_1[0]), /* 1 */
	asn_DEF_SessionConnectionIdentifier_tags_1,	/* Same as above */
	sizeof(asn_DEF_SessionConnectionIdentifier_tags_1)
		/sizeof(asn_DEF_SessionConnectionIdentifier_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SessionConnectionIdentifier_1,
	3,	/* Elements count */
	&asn_SPC_SessionConnectionIdentifier_specs_1	/* Additional specs */
};

