/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PRES"
 * 	found in "../../../../utils/ISO8823-PRESENTATION.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Typed_data_type_H_
#define	_Typed_data_type_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AC-PPDU.h"
#include "ACA-PPDU.h"
#include "User-data.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Typed_data_type_PR {
	Typed_data_type_PR_NOTHING,	/* No components present */
	Typed_data_type_PR_acPPDU,
	Typed_data_type_PR_acaPPDU,
	Typed_data_type_PR_ttdPPDU
} Typed_data_type_PR;

/* Typed-data-type */
typedef struct Typed_data_type {
	Typed_data_type_PR present;
	union Typed_data_type_u {
		AC_PPDU_t	 acPPDU;
		ACA_PPDU_t	 acaPPDU;
		User_data_t	 ttdPPDU;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Typed_data_type_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Typed_data_type;

#ifdef __cplusplus
}
#endif

#endif	/* _Typed_data_type_H_ */
#include <asn_internal.h>
