/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PRES"
 * 	found in "../../../../utils/ISO8823-PRESENTATION.asn"
 * 	`asn1c -fcompound-names`
 */

#include "User-data.h"

static asn_TYPE_member_t asn_MBR_User_data_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct User_data, choice.simply_encoded_data),
		(ASN_TAG_CLASS_APPLICATION | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Simply_encoded_data,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"simply-encoded-data"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct User_data, choice.fully_encoded_data),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Fully_encoded_data,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"fully-encoded-data"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_User_data_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 0, 0, 0 }, /* simply-encoded-data */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 1, 0, 0 } /* fully-encoded-data */
};
static asn_CHOICE_specifics_t asn_SPC_User_data_specs_1 = {
	sizeof(struct User_data),
	offsetof(struct User_data, _asn_ctx),
	offsetof(struct User_data, present),
	sizeof(((struct User_data *)0)->present),
	asn_MAP_User_data_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_User_data = {
	"User-data",
	"User-data",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_User_data_1,
	2,	/* Elements count */
	&asn_SPC_User_data_specs_1	/* Additional specs */
};

